name: gnome-recipes
version: 1.6.2
summary: GNOME loves to cook
description: |
  Recipes is an easy-to-use application that will help you to discover what to cook
  today, tomorrow, the rest of the week and for your special occasions.

  Recipes comes with a collection of recipes that have been collected by GNOME contributors
  from all over the world. It also lets you store your own recipes and share them with your
  friends.

  The major features of Recipes include:
    * Add and edit your own recipes
    * Share recipes with your friends
    * Export and print shopping lists
    * Adjust quantities based on the number of servings
    * Mark recipes to cook later or add them to your favorites
    * Add notes to recipes
    * Hands-free cooking instruction mode

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  gtk3-themes:
    interface: content
    target: $SNAP/usr/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/usr/share/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gnome-recipes:
    interface: dbus
    bus: session
    name: org.gnome.Recipes

apps:
  gnome-recipes:
    command: desktop-launch gnome-recipes
    plugs:
      - cups-control
      - avahi-observe
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.Recipes.desktop

parts:
  gnome-recipes:
    build-attributes: [no-system-libraries]
    after: [desktop-gnome-platform]
    source: https://git.gnome.org/browse/recipes
    source-type: git
    source-tag: 1.6.2
    prepare: |
      sed -i.bak -e 's|=org.gnome.Recipes$|=${SNAP}/meta/gui/org.gnome.Recipes.png|g' data/org.gnome.Recipes.desktop.in
      sed -i.bak -e 's|\])$|\], symlink_media: false)|g' help/meson.build
      sed -i.bak -e 's|DATADIR|"/snap/gnome-recipes/current/usr/share"|g' src/gr-appdata.c
      #sed -i.bak -e 's|.flatpak-info|meta/snap.yaml|g' src/gr-utils.c
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/512x512/org.gnome.Recipes.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp snapbuild/data/org.gnome.Recipes.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/usr, -Dautoar=yes]
    organize:
      snap/recipes/current/usr: usr
    build-packages:
      - appstream-util
      - gnome-pkg-tools
      - itstool
      - libcanberra-dev
      - libgirepository1.0-dev
      - libgspell-1-dev
      - libgtk-3-dev
      - libsoup-gnome2.4-dev
      - libgnome-autoar-0-dev
      - pkg-config
      - libjson-glib-dev
  libraries:
    plugin: nil
    stage-packages:
      - libgnome-autoar-0-0
      - libarchive13
    prime:
      - "usr/lib/*/libgnome-autoar-0.so*"
      - "usr/lib/*/libarchive.so*"
